# Generated by Django 5.1 on 2024-08-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_pc_brand_alter_pc_id_alter_pc_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='id',
            field=models.CharField(editable=False, max_length=5, primary_key=True, serialize=False),
        ),
    ]
