# Generated by Django 5.1 on 2024-08-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_pc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
